on: push
name: API extractor
jobs:
  # breakingChangeDetectionBot:
  #   name: Breaking change detection bot
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Breaking change detection bot
  #     uses: ./.github/api-extractor-action
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # lintingAndFixingStyles:
  #   name: Running prettier fix and than linting
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Prettier fix and ng lint run
  #     run: |
  #       yarn install
  #       npm run prettier-fix
  #       npm run lint
  # testingCoreLib:
  #   name: Testing core lib
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Testing core lib
  #     run: |
  #       yarn install
  #       npm run test:core:lib:ci
  testingE2E:
    name: Testing app with e2e
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: TTTTT
        run: |
          yarn install
          yarn build:core:lib
          yarn build
          yarn add serve --no-save
          yarn add concurrently --no-save
          cd projects/storefrontapp-e2e-cypress && yarn && cd ../..
          yarn test:action
  # buildingProjects:
  #   name: Building core lib and app
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Core lib build and app build
  #     run: |
  #       yarn install
  #       npm run build:core:lib
  #       npm run build
